apiVersion: v1
kind: Pod
metadata:
  name: netology-web
  labels:
    app: netology-web
spec:
  containers:
    - name: echoserver
      image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
      ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: netology-svc
spec:
  type: ClusterIP
  selector:
    app: netology-web
  ports:
    - name: http
      port: 80
      targetPort: 8080
